const fs = require('fs');
const { execSync } = require('child_process');
const config = require('../config');
const db = require('../lib/database');

/**
 * Export command - generate move commands script
 */
function run(args) {
  if (!fs.existsSync(config.paths.database)) {
    console.log('No database found. Run "scan" first.');
    return;
  }
  
  const defaultFile = config.isWindows ? 'move_commands.bat' : 'move_commands.sh';
  const outputFile = args[0] || defaultFile;
  
  db.init();
  const ops = db.getPendingOperations();
  
  if (ops.length === 0) {
    console.log('No pending operations to export.');
    db.close();
    return;
  }
  
  let script;
  if (config.isWindows) {
    script = `@echo off
REM Generated by video-tagger
REM ${ops.length} operations
REM Review carefully before running!

${ops.map(o => o.command).join('\n')}

echo Done! Moved ${ops.length} files.
pause
`;
  } else {
    script = `#!/bin/bash
# Generated by video-tagger
# ${ops.length} operations
# Review carefully before running!

set -e  # Exit on error

${ops.map(o => o.command).join('\n')}

echo "Done! Moved ${ops.length} files."
`;
  }
  
  fs.writeFileSync(outputFile, script);
  
  if (!config.isWindows) {
    try {
      execSync(`chmod +x "${outputFile}"`);
    } catch {
      // Ignore chmod errors
    }
  }
  
  console.log(`Exported ${ops.length} operations to: ${outputFile}`);
  console.log(`Review the file, then run: ${config.isWindows ? outputFile : './' + outputFile}`);
  
  db.close();
}

module.exports = { run };
